### ISSUE TITLE
quora-upvotes extension no longer working , sorting is not occurring based on upvotes.

### ISSUE THREAD

**Issue by seshgirik** [evansendra/quora-upvotes#7]
Hi 

quora-upvotes extension is no longer working , seems quora site has changed something.
sorting is not occurring based on upvotes.
Pl resolve this issue.

Regards
Sesh

**Comment by VelcroNebula** [comment]
Yup, quora-upvotes extension is no longer working

**Comment by AmirShehzadDev** [comment]
yes. quora has updated design of their website. so this extension is no longer working

**Comment by VelcroNebula** [comment]
I’m currently using: Quora Quick Sort — which it’s last update is since May
2018.

On June 12, 2018 at 5:19:54 AM, amir-shehzad (notifications@github.com)
wrote:

yes. quora has updated design of their website. so this extension is no
longer working

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/evansendra/quora-upvotes/issues/7#issuecomment-396524032>,
or mute the thread

**Comment by evansendra** [comment]
Unpublishing for now until I get some time to update the extension.  Thanks all.  As @stamatgeorge mentioned, there's a great alternative available via [Quora Quick Sort](https://chrome.google.com/webstore/detail/quora-quick-sort/baflgahbjendijbflolilmdpghedfadp?hl=en).

**Comment by phenox22** [comment]
Quick sort is unavailable.
